name: Update IBAMA SQLite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Setup Git LFS
        run: |
          git lfs install
          git lfs pull

      - name: Sync with remote before build
        run: |
          git fetch origin main
          git checkout -B main
          git rebase origin/main || true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pandas

      - name: Build SQLite from IBAMA ZIP
        run: |
          PYTHONUNBUFFERED=1 python -u -W "ignore:Parsing dates in %Y-%m-%d format.*:UserWarning" backend/build_static_db.py

      - name: Publish build summary
        if: always()
        run: |
          if [ -f build_summary.md ]; then
            cat build_summary.md >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No build_summary.md generated" >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Commit updated SQLite (gzip) if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public-data/ibama.sqlite.gz
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update IBAMA SQLite ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git fetch origin main
            git pull --rebase origin main || true
            git push origin HEAD:main || (git pull --rebase origin main && git push origin HEAD:main)
          fi
