name: Update IBAMA SQLite

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

permissions:
  contents: write

jobs:
  build-and-commit:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install pandas

      - name: Build SQLite from IBAMA ZIP
        run: |
          python backend/build_static_db.py

      - name: Commit updated SQLite if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public-data/ibama.sqlite
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update IBAMA SQLite ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          fi
